### ISSUE TITLE
New version compile error from new verison of git

### ISSUE THREAD

**Issue by raw937** [hallamlab/FragGeneScanPlus#8]
command > git clone https://github.com/hallamlab/FragGeneScanPlus.git
command > make clean
out - rm -rf util_lib.o hmm_lib.o run_hmm.o  fasta.o FGS+  
command > make
out - gcc  -O3 -m64 -w -c util_lib.c 
util_lib.c: In function ‘stopMemset’:
util_lib.c:422: error: ‘for’ loop initial declarations are only allowed in C99 mode
util_lib.c:422: note: use option -std=c99 or -std=gnu99 to compile your code
make: **\* [util_lib.o] Error 1

**Comment by raw937** [comment]
Works with a gcc/6.1.0 not gcc/4.9.2

**Comment by dongjaek** [comment]
fixed.
